# Generated by Django 2.0.2 on 2019-04-23 11:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('sexo', models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho')], max_length=2, verbose_name='Sexo')),
                ('raza', models.CharField(max_length=200, verbose_name='Raza')),
                ('nacimiento', models.IntegerField(default=2000, verbose_name='Año de nacimiento')),
                ('size', models.CharField(choices=[('Toy/Enano', '< 5 kg'), ('Pequeño', '5 - 14 kg'), ('Mediano', '14 - 25 kg'), ('Grande', '25 - 50 kg'), ('Gigante', '> 50 kg')], default='Mediano', max_length=10, verbose_name='Tamaño')),
                ('color', models.CharField(max_length=200, verbose_name='Color')),
                ('foto', models.ImageField(upload_to='perros', verbose_name='Foto')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Mas información')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'perro',
                'verbose_name_plural': 'perros',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
