# Generated by Django 2.0.2 on 2019-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_auto_20190423_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(max_length=30, verbose_name='Raza'),
        ),
    ]
