# Generated by Django 2.0.2 on 2019-05-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0003_auto_20190427_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perros', verbose_name='Foto'),
        ),
    ]
