# Generated by Django 2.0.2 on 2019-05-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0004_auto_20190502_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(upload_to='perros', verbose_name='Foto'),
        ),
    ]
