# Generated by Django 2.0.2 on 2019-05-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0005_auto_20190506_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perro',
            options={'ordering': ['-updated'], 'verbose_name': 'perro', 'verbose_name_plural': 'perros'},
        ),
    ]
