# Generated by Django 2.0.2 on 2019-05-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0006_auto_20190517_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Provincia')),
            ],
        ),
    ]
