# Generated by Django 2.0.2 on 2019-05-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0008_auto_20190518_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
