# Generated by Django 2.0.2 on 2019-05-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0010_provincia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
