# Generated by Django 2.0.2 on 2019-05-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_provincia'),
        ('perros', '0011_delete_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='provincia',
            field=models.ForeignKey(default='50', on_delete=django.db.models.deletion.CASCADE, to='core.Provincia', verbose_name='Responsable'),
        ),
    ]
