# Generated by Django 2.0.2 on 2019-05-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0012_perro_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='provincia',
            field=models.ForeignKey(default='50', on_delete=django.db.models.deletion.CASCADE, to='core.Provincia', verbose_name='Provincia'),
        ),
    ]
