# Generated by Django 2.0.2 on 2019-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0013_auto_20190518_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
