# Generated by Django 2.0.2 on 2019-05-25 19:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('foto', models.ImageField(upload_to='noticias', verbose_name='Foto')),
                ('fechaNoticia', models.DateField(verbose_name='Fecha de la noticia')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Mas información')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('provincia', models.ForeignKey(default='50', on_delete=django.db.models.deletion.CASCADE, to='core.Provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['fechaNoticia'],
            },
        ),
        migrations.CreateModel(
            name='TipoNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=2, verbose_name='Tipo Noticia')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre tipo Noticia')),
            ],
            options={
                'verbose_name': 'tipo de noticia',
                'verbose_name_plural': 'tipos de noticias',
                'ordering': ['tipo'],
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='tiponoticia',
            field=models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, to='noticias.TipoNoticia', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
