# Generated by Django 2.0.2 on 2019-05-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_provincia'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='provincia',
            field=models.ForeignKey(default='50', on_delete=django.db.models.deletion.CASCADE, to='core.Provincia', verbose_name='Provincia'),
        ),
    ]
